#!/usr/bin/ksh


if (($#!=1))
then
	echo "usuage: $0 branch_name"
	exit 1
fi
cd src
git checkout $1

if (($? != 0))
then
	echo  Error: $0: git checkout $1, errInfo=$errInfo
	exit 1
fi

rel_dir=/home/chm/work/system-daemons.ut.release/${1}_`date "+%Y%m%d_%H%M%S"`
export rel_dir
mkdir -p ${rel_dir}
make
make install
make clean
echo `pwd`
