all:
	make -C stm3210x_bulk_inc1
	make -C bsd_powerlab_client
	make -C powerlab_client
install:
	make -C stm3210x_bulk_inc1 install
	make -C bsd_powerlab_client install
	make -C powerlab_client install
clean:
	make -C stm3210x_bulk_inc1 clean
	make -C bsd_powerlab_client clean
	make -C powerlab_client clean

